### ISSUE TITLE
помощь

### ISSUE THREAD

**Issue by ziben87** [vuchastyi/privatbank_Opencart_PayParts#1]
Добрый день!! помоги разобраться выдает ошибку такую Fatal error: Class 'Controllerpaymentpbpp' not found in /home/dessange/brenta.com.ua/www/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php on line 36

**Comment by vuchastyi** [comment]
Можете описать, как возникла данная ошибка?
Последовательность действий, которые вы выполнили, до возникновения данной ошибки?
Какая версия PHP стоит?

**Comment by ziben87** [comment]
смотрите сначала я загрузил ваши файлы просто на сервер но оплата не появлялась вообще

**Comment by ziben87** [comment]
потом я залил с payment в payment и появилось тоесть там как то у вас файлы не правильно лежат и я думаю что из за этого оно как то не находит

**Comment by ziben87** [comment]
потом я все удалил залил заново и все равно эта же ошибка

**Comment by vuchastyi** [comment]
Вы пробовали выкачать архив последней(это же и первая версия) плагина на странице https://github.com/vuchastyi/privatbank_Opencart_PayParts/releases?
На этой странице есть два формата в которых вы можете сохранить этот репозиторий к себе на компьютер(zip, tar.gz), вы можете выбрать более удобный для вас.

**Короткая инструкция по устновке:**
Затем в админ панели сайта на странице Дополнения > Установка дополнений([/admin/index.php?route=extension/installer](#)) загрузить и установить плагин.

**Comment by ziben87** [comment]
я когда так пробую то говорит не верный формат

**Comment by ziben87** [comment]
privatbank_Opencart_PayParts-0.0.1

**Comment by ziben87** [comment]
Неправильный тип файла!

**Comment by ziben87** [comment]
так что не надо было файлы заливать на сервер! но через загрузчик
пишет Неправильный
тип файла!

14 декабря 2017 г., 17:05 пользователь Igor Vuchastyi <
notifications@github.com> написал:

**Comment by vuchastyi** [comment]
завтра смогу посмотреть и возможно решить вашу проблему

**Comment by ziben87** [comment]
ок спасибо большое!

**Comment by vuchastyi** [comment]
Closes #2

**Comment by vuchastyi** [comment]
Какая у вас версия opencart?

**Comment by ziben87** [comment]
2,2

**Comment by vuchastyi** [comment]
В этом и проблема, данная версия плагина совместима только с версиями Opencart v3.x

**Comment by ziben87** [comment]
и что делать?

**Comment by vuchastyi** [comment]
Насколько я знаю, версии данного плагина для Opencart 2.x ещё не существует. Существует для версий 1.5.х, 3.х. В вашем случае это решается обновлением Opencart и установкой на него данного плагина.
Если при установке на Opencart 3.x возникнет снова ошибка - обращайтесь.

**Comment by ziben87** [comment]
та боюсь что если обновлю опен карт то слетят другие модули ((

**Comment by vuchastyi** [comment]
Тогда наймите программиста, который грамотно перенесёт все ваши модули и установит данный плагин. Больше я Вам ни чем не смогу помочь.

**Comment by ziben87** [comment]
ок спасибо!
